development:
  adapter: postgresql
  host: db
  username: postgres
  database: barcoder_dev
  pool: 100

test:
  adapter: postgresql
  host: db
  username: postgres
  database: barcoder_tst
  pool: 100
